### ISSUE TITLE
Add Database

### ISSUE THREAD

**Issue by sgibson19** [carlosricov/Flask-Practice-Typer-Team3#15]
Need to add a database, any suggestions are welcome

**Comment by carlosricov** [comment]
I know before postgres we used mysql. I found it simpler to understand and use however I think it's con is speed. We could try MySQL and if anything switch to postgres? @CarlosHurand what do you think?

**Comment by CarlosHurand** [comment]
Sounds great, as far as I know if we do a decent job MySQL wouldn't even be that slow, so I'll say let's give it a shot
