### ISSUE TITLE
Login & Register Pages Need Back to Home feature

### ISSUE THREAD

**Issue by carlosricov** [carlosricov/Flask-Practice-Typer-Team3#18]
Currently, there's no way to return to the home page. Should we add a nav bar to these pages? What do you guys think @sgibson19 @CarlosHurand ?

**Comment by sgibson19** [comment]
I agree @carlosricov  @CarlosHurand

**Comment by CarlosHurand** [comment]
Me too! @carlosricov @sgibson19
